# Site settings
title: Joy C. Opsvig
description: Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.joyopsvig.com"

# User settings
username: Joy C. Opsvig
user_description: Aspiring data scientist with strong background in public relations and communications.</br/></br/>I fell in love with data science while working with leading economists and data scientists at Upwork, LinkedIn, and Tinder. I found a niche for myself at my agency, helping mine our clients’ data and research reports and translating these findings into compelling stories.
user_title: Data Scientist
email: joyopsvig@gmail.com
# twitter_username: lorem_ipsum
github_username:  joycorrine
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
